apiVersion: v1
kind: Pod
metadata:
  name: billrun
spec:
  restartPolicy: Never
  containers:
    - name: task
      image: lzetea.azurecr.io/springcloudtask/billrun:2.0.0-SNAPSHOT
      
      env:
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: database-password
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mariadb://mariadb:3306/task
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: org.mariadb.jdbc.Driver
        - name: SPRING_BATCH_JDBC_INITIALIZE-SCHEMA
          value: always
        - name: SPRING_SQL_INIT_MODE
          value: always
  initContainers:
    - name: init-mariadb-database
      image: mariadb:10.4.22
      env:
        - name: MARIADB_PWD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: database-password
      command:
        [
          'sh',
          '-c',
          'mariadb -h mariadb -u root --password=$MARIADB_PWD -e "CREATE DATABASE IF NOT EXISTS task;"',
        ]